# Numpy ile veri okuma

NumPy modülü ile dosyalardan veri okumak mümkündür ve özellikle sayısal veriler üzerinde çalışıyorsanız çok etkilidir. NumPy, genellikle CSV (Comma Separated Values) gibi dosyalardan hızlı ve verimli bir şekilde veri okumak için kullanılır.

### 1. numpy.loadtxt(): 
Metin Dosyalarından Veri Okuma
Bu fonksiyon, genellikle düzenli olarak yapılandırılmış sayısal veriler içeren düz metin dosyalarını okumak için kullanılır.

In [5]:
import numpy as np

# Veriyi 'dosya.txt' dosyasından yükle
dosya = 'C:/Users/ASUS/Desktop/Ders/Python_ile_veri_bilimi/iris.data.txt'


In [11]:
veri=np.loadtxt(dosya,delimiter=',',usecols=(0, 1, 2, 3))
print(veri)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

veri=np.loadtxt(dosya,delimiter=',',skiprows=4)

Eğer normal okuma yapmak istesek hata verecek çünkü  np.loadtxt() fonksiyonunun veriyi sayısal (float) olarak okumaya çalıştığı, ancak veri içinde bir dize (örneğin 'Iris-setosa' gibi) olduğu için bunu başaramadığı durumlarda ortaya çıkar. Yani, loadtxt() sadece sayısal verilerle çalışabilir ve veri setinizde sayısal olmayan değerler (dizeler/stringler) varsa bu hata meydana gelir.

# 2. numpy.genfromtxt():
Eksik Verilerle Başa Çıkma
Bu fonksiyon, loadtxt() fonksiyonuna benzer, ancak eksik verilerle başa çıkabilme yeteneğine sahiptir. Eğer dosyada bazı hücreler boşsa, bu hücreler için belirli bir değer atanabilir (örneğin, NaN).

In [12]:
import numpy as np

# Eksik veriler içeren dosya
veri = np.genfromtxt('iris.data.txt', delimiter=',', dtype=float)

print(veri)

[[5.1 3.5 1.4 0.2 nan]
 [4.9 3.  1.4 0.2 nan]
 [4.7 3.2 1.3 0.2 nan]
 [4.6 3.1 1.5 0.2 nan]
 [5.  3.6 1.4 0.2 nan]
 [5.4 3.9 1.7 0.4 nan]
 [4.6 3.4 1.4 0.3 nan]
 [5.  3.4 1.5 0.2 nan]
 [4.4 2.9 1.4 0.2 nan]
 [4.9 3.1 1.5 0.1 nan]
 [5.4 3.7 1.5 0.2 nan]
 [4.8 3.4 1.6 0.2 nan]
 [4.8 3.  1.4 0.1 nan]
 [4.3 3.  1.1 0.1 nan]
 [5.8 4.  1.2 0.2 nan]
 [5.7 4.4 1.5 0.4 nan]
 [5.4 3.9 1.3 0.4 nan]
 [5.1 3.5 1.4 0.3 nan]
 [5.7 3.8 1.7 0.3 nan]
 [5.1 3.8 1.5 0.3 nan]
 [5.4 3.4 1.7 0.2 nan]
 [5.1 3.7 1.5 0.4 nan]
 [4.6 3.6 1.  0.2 nan]
 [5.1 3.3 1.7 0.5 nan]
 [4.8 3.4 1.9 0.2 nan]
 [5.  3.  1.6 0.2 nan]
 [5.  3.4 1.6 0.4 nan]
 [5.2 3.5 1.5 0.2 nan]
 [5.2 3.4 1.4 0.2 nan]
 [4.7 3.2 1.6 0.2 nan]
 [4.8 3.1 1.6 0.2 nan]
 [5.4 3.4 1.5 0.4 nan]
 [5.2 4.1 1.5 0.1 nan]
 [5.5 4.2 1.4 0.2 nan]
 [4.9 3.1 1.5 0.1 nan]
 [5.  3.2 1.2 0.2 nan]
 [5.5 3.5 1.3 0.2 nan]
 [4.9 3.1 1.5 0.1 nan]
 [4.4 3.  1.3 0.2 nan]
 [5.1 3.4 1.5 0.2 nan]
 [5.  3.5 1.3 0.3 nan]
 [4.5 2.3 1.3 0.3 nan]
 [4.4 3.2 1.3 0.2 nan]
 [5.  3.5 1

usecols, numpy.loadtxt() ve numpy.genfromtxt() gibi fonksiyonlarda kullanılan bir parametredir ve dosyadan hangi sütunların okunacağını belirtmek için kullanılır. Bu sayede, dosyadaki belirli sütunları seçip yalnızca bu sütunları yükleyerek bellekte yer ve işlem süresi tasarrufu sağlanabilir.

usecols Parametresinin Kullanımı:
Tip: usecols, bir tamsayı dizisi, liste veya tuple olabilir.
Amaç: Belirli sütunları seçerek sadece o sütunların yüklenmesini sağlar.

In [22]:
import numpy as np

# İlk üç sütunu okur (0, 1, 2 numaralı sütunlar)
veri = np.loadtxt('iris.data.txt', delimiter=',', usecols=(0, 1, 2,3))

print(veri)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

# Önemli Not:

Çoğu zaman okuyacağımız tabloda farklı türdeki veri sütunları yer alabilir. Bu durumda .loadtxt() yerine .genfromtxt() metodu kullanılır. Bu metodda dtype=None olarak belirtirsek program her sütundaki veri tipini otomatik olarak belirlemeye çalışarak ilerler. Numpy diziler aynı türde verilerden oluşmak durumundadır. Bu nedenle farklı türdeki verileri okuduğumuz zaman dizilerden oluşan bir dizi elde edilir. Ana diziyi oluşturan diziler verinin her satırını ifade eder. 

In [29]:
import numpy as np
dosya='iris.data.txt'
veri = np.genfromtxt(dosya, delimiter='\t',dtype=None)
print(veri)

[b'5.1,3.5,1.4,0.2,Iris-setosa' b'4.9,3.0,1.4,0.2,Iris-setosa'
 b'4.7,3.2,1.3,0.2,Iris-setosa' b'4.6,3.1,1.5,0.2,Iris-setosa'
 b'5.0,3.6,1.4,0.2,Iris-setosa' b'5.4,3.9,1.7,0.4,Iris-setosa'
 b'4.6,3.4,1.4,0.3,Iris-setosa' b'5.0,3.4,1.5,0.2,Iris-setosa'
 b'4.4,2.9,1.4,0.2,Iris-setosa' b'4.9,3.1,1.5,0.1,Iris-setosa'
 b'5.4,3.7,1.5,0.2,Iris-setosa' b'4.8,3.4,1.6,0.2,Iris-setosa'
 b'4.8,3.0,1.4,0.1,Iris-setosa' b'4.3,3.0,1.1,0.1,Iris-setosa'
 b'5.8,4.0,1.2,0.2,Iris-setosa' b'5.7,4.4,1.5,0.4,Iris-setosa'
 b'5.4,3.9,1.3,0.4,Iris-setosa' b'5.1,3.5,1.4,0.3,Iris-setosa'
 b'5.7,3.8,1.7,0.3,Iris-setosa' b'5.1,3.8,1.5,0.3,Iris-setosa'
 b'5.4,3.4,1.7,0.2,Iris-setosa' b'5.1,3.7,1.5,0.4,Iris-setosa'
 b'4.6,3.6,1.0,0.2,Iris-setosa' b'5.1,3.3,1.7,0.5,Iris-setosa'
 b'4.8,3.4,1.9,0.2,Iris-setosa' b'5.0,3.0,1.6,0.2,Iris-setosa'
 b'5.0,3.4,1.6,0.4,Iris-setosa' b'5.2,3.5,1.5,0.2,Iris-setosa'
 b'5.2,3.4,1.4,0.2,Iris-setosa' b'4.7,3.2,1.6,0.2,Iris-setosa'
 b'4.8,3.1,1.6,0.2,Iris-setosa' b'5.4,3.4,1.5,0.4,Iris-

C:\Users\ASUS\AppData\Local\Temp\ipykernel_1916\2075092050.py:3: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  veri = np.genfromtxt(dosya, delimiter='\t',dtype=None)


# CSV Dosyasını Okuma
CSV dosyasındaki verileri NumPy ile hızlı bir şekilde yükleyebilirsiniz. csv.reader() gibi yöntemler yerine NumPy'yi kullanarak verileri sayısal olarak işlemeniz daha kolay olabilir. recfromcsv gibi bir metod ilede okuma yapabilirsiniz

In [31]:
veri = np.genfromtxt('iris.csv', delimiter=',', skip_header=1, dtype=float)
print(veri)

[[5.1 3.5 1.4 0.2 nan]
 [4.9 3.  1.4 0.2 nan]
 [4.7 3.2 1.3 0.2 nan]
 [4.6 3.1 1.5 0.2 nan]
 [5.  3.6 1.4 0.2 nan]
 [5.4 3.9 1.7 0.4 nan]
 [4.6 3.4 1.4 0.3 nan]
 [5.  3.4 1.5 0.2 nan]
 [4.4 2.9 1.4 0.2 nan]
 [4.9 3.1 1.5 0.1 nan]
 [5.4 3.7 1.5 0.2 nan]
 [4.8 3.4 1.6 0.2 nan]
 [4.8 3.  1.4 0.1 nan]
 [4.3 3.  1.1 0.1 nan]
 [5.8 4.  1.2 0.2 nan]
 [5.7 4.4 1.5 0.4 nan]
 [5.4 3.9 1.3 0.4 nan]
 [5.1 3.5 1.4 0.3 nan]
 [5.7 3.8 1.7 0.3 nan]
 [5.1 3.8 1.5 0.3 nan]
 [5.4 3.4 1.7 0.2 nan]
 [5.1 3.7 1.5 0.4 nan]
 [4.6 3.6 1.  0.2 nan]
 [5.1 3.3 1.7 0.5 nan]
 [4.8 3.4 1.9 0.2 nan]
 [5.  3.  1.6 0.2 nan]
 [5.  3.4 1.6 0.4 nan]
 [5.2 3.5 1.5 0.2 nan]
 [5.2 3.4 1.4 0.2 nan]
 [4.7 3.2 1.6 0.2 nan]
 [4.8 3.1 1.6 0.2 nan]
 [5.4 3.4 1.5 0.4 nan]
 [5.2 4.1 1.5 0.1 nan]
 [5.5 4.2 1.4 0.2 nan]
 [4.9 3.1 1.5 0.2 nan]
 [5.  3.2 1.2 0.2 nan]
 [5.5 3.5 1.3 0.2 nan]
 [4.9 3.6 1.4 0.1 nan]
 [4.4 3.  1.3 0.2 nan]
 [5.1 3.4 1.5 0.2 nan]
 [5.  3.5 1.3 0.3 nan]
 [4.5 2.3 1.3 0.3 nan]
 [4.4 3.2 1.3 0.2 nan]
 [5.  3.5 1

In [35]:
veri=np.recfromcsv('iris.csv', delimiter='\t',  dtype=None)
print(veri)

[(b'5.1,3.5,1.4,.2,"Setosa"',) (b'4.9,3,1.4,.2,"Setosa"',)
 (b'4.7,3.2,1.3,.2,"Setosa"',) (b'4.6,3.1,1.5,.2,"Setosa"',)
 (b'5,3.6,1.4,.2,"Setosa"',) (b'5.4,3.9,1.7,.4,"Setosa"',)
 (b'4.6,3.4,1.4,.3,"Setosa"',) (b'5,3.4,1.5,.2,"Setosa"',)
 (b'4.4,2.9,1.4,.2,"Setosa"',) (b'4.9,3.1,1.5,.1,"Setosa"',)
 (b'5.4,3.7,1.5,.2,"Setosa"',) (b'4.8,3.4,1.6,.2,"Setosa"',)
 (b'4.8,3,1.4,.1,"Setosa"',) (b'4.3,3,1.1,.1,"Setosa"',)
 (b'5.8,4,1.2,.2,"Setosa"',) (b'5.7,4.4,1.5,.4,"Setosa"',)
 (b'5.4,3.9,1.3,.4,"Setosa"',) (b'5.1,3.5,1.4,.3,"Setosa"',)
 (b'5.7,3.8,1.7,.3,"Setosa"',) (b'5.1,3.8,1.5,.3,"Setosa"',)
 (b'5.4,3.4,1.7,.2,"Setosa"',) (b'5.1,3.7,1.5,.4,"Setosa"',)
 (b'4.6,3.6,1,.2,"Setosa"',) (b'5.1,3.3,1.7,.5,"Setosa"',)
 (b'4.8,3.4,1.9,.2,"Setosa"',) (b'5,3,1.6,.2,"Setosa"',)
 (b'5,3.4,1.6,.4,"Setosa"',) (b'5.2,3.5,1.5,.2,"Setosa"',)
 (b'5.2,3.4,1.4,.2,"Setosa"',) (b'4.7,3.2,1.6,.2,"Setosa"',)
 (b'4.8,3.1,1.6,.2,"Setosa"',) (b'5.4,3.4,1.5,.4,"Setosa"',)
 (b'5.2,4.1,1.5,.1,"Setosa"',) (b'5.5,4.2,1.