In [2]:
import numpy as np
a=np.array([1,2,3,4,5,6])

In [4]:
type(a)

numpy.ndarray

In [8]:
liste1=[1,2,3,4]
liste2=np.array(liste1)
#burada liste1 diye bir liste oluşturduk
#daha sonra liste2 ye liste1'i numpy'a dönüştürüp atadık.

In [6]:
type(liste2)

numpy.ndarray

In [9]:
liste3=(1,2,3,4,5)

In [10]:
type(liste3)

tuple

In [11]:
liste4=np.array(liste3)
#burada tuple olarak tanımladığımız liste3'ü liste4 e atayıp
#liste4 u numpy dizisine dönüştürdük

In [12]:
type(liste4)

numpy.ndarray

In [13]:
for i in liste4:
    print(type(i))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [18]:
a=np.array([1,2,3,4,5,6,7,8.2])

In [20]:
for i in a:
    print(type(i))
#örneğin burada 8.2 gibi bir float değer tanımladık
#bu değerin bu numpy dizisi içinde olması tamamen 
#veri tipinin değişmesine sebep oldu ve 
#tüm veri setinin veri tipi float olmuş oldu

<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>


In [21]:
a=np.array([1,2,3,4,5,8.2],dtype="int32")
for i in a:
    print(type(i))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


Bu şekilde istersek kendimizde daha sonra dizinin sonuna veri tipini belirtebiliriz. Fakat bu yöntem çok tercih edilmez. Çünkü veri kaybına yol açabilir

In [22]:
np.zeros(10,dtype="int8")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

Bazı durumlarda sadece 0'lardan oluşan bir numpy dizisi oluşturmamız gerekebilir bu gibi durumlarda np.zeros fonksiyonunu kullanırız. Örneğin bu tuval için bir veriyle veri tipi 2^8 yani 256 olmalı bu yüzden dtype int8 olarak belirtmemiz gerekti.

In [23]:
np.ones(10,dtype="int8")

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

np.ones fonksiyonu ise sadece 1 lerden oluşan bir dizi tanımlamaya yarar.

In [24]:
np.ones(12)*6

array([6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.])

burada aritmetik operatörlerden çarpmayı kullandık ve 1'i 6 ile çarptık bu sayede 6 lardan oluşan bir numpy dizisi oluşturduk.

In [25]:
np.full(14,2)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

Full fonksiyonunda ise ilk kısımda kaç adet olacağı ve ikinci kısımda hangi değer olacağını belirterek burada yaptığımız gibi 14 tane 2'lerden oluşan bir numpy dizisi tanımlayabiliriz.