NumPy, matris oluşturmak ve işlemler yapmak için etkili bir araçtır. NumPy'de matrisler, iki boyutlu diziler (ndarray) olarak temsil edilir. Aşağıda NumPy kullanarak farklı yöntemlerle matris oluşturma yöntemleri açıklanmıştır:

### 1. Elle Veri Girerek Matris Oluşturma
Diziler kullanılarak manuel olarak matris oluşturulabilir.

In [3]:
import numpy as np
a=np.array([[1,2,3],
           [4,5,6],
           [7,8,9]])
print(a)
#bu örnekte 3x3 boyutunda bir matris oluşturmuş olduk.

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 2. Sıfırdan Matris Oluşturma
np.zeros() metodu ile sıfırlardan oluşan bir matris oluşturabilirsiniz.

In [5]:
b=np.zeros((3,3))
print(b)
#bu kod ile 3x3 boyutlarında 0'lardan oluşan 
#bir matris oluşturmuş oluyoruz

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### 3. Birlerden Matris Oluşturma
np.ones() metodu ile birlerden oluşan bir matris oluşturabilirsiniz.

In [8]:
c=np.ones((3,4))
print(c)
#bu kod ile 3x4 boyutunda 1'lerden oluşan
#bir matris oluşturulmuş olur

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 4. Belirli Bir Değerle Doldurulmuş Matris
np.full() metodu ile bir matrisi istediğiniz değerle doldurabilirsiniz.

In [10]:
d=np.full((4,5),7)
print(d)
#bu kod ile 4x5 boyutlarında 7'lerden 
#oluşan bir matris oluşturmuş oluyoruz.

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


### 5. Rastgele Sayılarla Matris
np.random.rand() ve np.random.randint() rastgele değerlerle matrisler oluşturur.

In [12]:
e=np.random.rand(3,3)
print(e)
#0 ile 1 arasındaki değerlerden 3x3 boyutlarında
#bir matris oluşturmuş oluyoruz

[[0.7455033  0.68070819 0.90620482]
 [0.88552025 0.57474779 0.86585762]
 [0.34834248 0.95664255 0.56770355]]


In [14]:
f=np.random.randint(1,10,(4,4))
print(f)
"""Bu kod sayesinde 1 ile 10 arasında değerlerden oluşan 4x4 boyutunda
bir matris oluşturmuş oluyoruz"""

[[9 7 4 7]
 [8 4 5 7]
 [4 4 6 1]
 [8 5 5 8]]


'Bu kod sayesinde 1 ile 10 arasında değerlerden oluşan 4x4 boyutunda\nbir matris oluşturmuş oluyoruz'

### 6. Birim Matris
np.eye() ile birim matris (köşegenin 1 olduğu matris) oluşturabilirsiniz. 

In [15]:
g=np.eye(3)
print(g)
"""bu kod ile 3x3 boyutunda köşegen matris yani sol üst ve sağ
alt çapraz değerler arası 1 diğer değerleri 0 olan matris oluşturulmuş olur """


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


'bu kod ile 3x3 boyutunda köşegen matris yani sol üst ve sağ\nalt çapraz değerler arası 1 diğer değerleri 0 olan matris oluşturulmuş olur '

### 7. Ardışık Sayılarla Matris
np.arange() ve np.reshape() ile ardışık sayılar kullanarak matris oluşturabilirsiniz. 

In [16]:
h=np.arange(1,10).reshape(3,3)
print(h)
"""Bu kod sayesinde 1 den 10'a kadar değerlerden sol üstten 
başlayarak devam eden 3x3 boyutunda bir matris oluşturulmuş olur
"""

[[1 2 3]
 [4 5 6]
 [7 8 9]]


"Bu kod sayesinde 1 den 10'a kadar değerlerden sol üstten \nbaşlayarak devam eden 3x3 boyutunda bir matris oluşturulmuş olur\n"

### 8. Satır veya Sütun Tekrarıyla Matris
np.tile() bir dizi veya satırı tekrar ederek matris oluşturabilir. 

In [17]:
k=np.tile([1,2,3],(3,1))
print(k)
"""Bu kod ile 1,2,3 matrisini 3x1 boyutuna uygun olma 
şartıyla yani tane 3x1 boyutunda bir matrise doldurur."""

[[1 2 3]
 [1 2 3]
 [1 2 3]]


'Bu kod ile 1,2,3 matrisini 3x1 boyutuna uygun olma \nşartıyla yani tane 3x1 boyutunda bir matrise doldurur.'

### 9. Köşegen (Diagonal) Matris
np.diag() ile köşegen matris oluşturabilirsiniz.

In [18]:
l=np.diag([1,2,3])
print(l)
"""Bu kod sayesinde köşegenindeki değerleri sırasıyla
1 2 3 olan 3x3 boyutunda bir matris oluşturulmuş olur"""

[[1 0 0]
 [0 2 0]
 [0 0 3]]


'Bu kod sayesinde köşegenindeki değerleri sırasıyla\n1 2 3 olan 3x3 boyutunda bir matris oluşturulmuş olur'

### 10. Boş Matris
np.empty() ile içeriği rastgele, ancak bellek alanı ayrılmış bir matris oluşturabilirsiniz.

In [20]:
m=np.empty((2,3))
print(m)
""" 2x3 boyutunda boş bir matris oluşturulur"""

[[0. 0. 0.]
 [0. 0. 0.]]


' 2x3 boyutunda boş bir matris oluşturulur'