NumPy, matematiksel, istatistiksel ve veri işleme ile ilgili birçok özel fonksiyon ve metot sunar. Bu fonksiyonlar ve metotlar, büyük veri setleri üzerinde hızlı ve verimli işlemler yapmaya olanak tanır. İşte NumPy'nin en sık kullanılan özel fonksiyonları ve metodları

# Matematiksel Fonksiyonlar
Bu fonksiyonlar matematiksel işlemler yapmak için kullanılır:

### 1)Trigonometri Fonksiyonları 

In [2]:
import numpy as np
x=np.array([0,np.pi/2,np.pi])
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))
#sinüs, cosinüs, tanjant gibi değerlerin hesaplanmasında kullanılır

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


### 2)Üstel ve Logaritmik Fonksiyonlar 

In [4]:
print(np.exp([1,2,3]))
print(np.log([1,np.e,np.e**2]))
print(np.log10([1,10,100]))
"""Taban belirtilmezse tabanı e olarak kabul edilir."""

[ 2.71828183  7.3890561  20.08553692]
[0. 1. 2.]
[0. 1. 2.]


'Taban belirtilmezse tabanı e olarak kabul edilir.'

### 3)Karekök ve Üs Alma 

In [6]:
print(np.sqrt([1,2,3]))
#karekök alır
print(np.power([2,3],3))
#ilk girilen matris değerleri ikinci ise üssün derecesi burada 3

[1.         1.41421356 1.73205081]
[ 8 27]


### 4)Yuvarlama Fonksiyonları

In [7]:
print(np.round([1.4,1.5,1.6]))
print(np.floor([1,4,1.5,1.6]))
print(np.ceil([1.4,1.5,1.6]))

[1. 2. 2.]
[1. 4. 1. 1.]
[2. 2. 2.]


# İstatistiksel Fonksiyonlar
### 1)Temel İstatistiksel İşlemler

In [9]:
veri=np.array([1,2,3,4,5])
print(np.mean(veri)) #Ortalamayı hesaplar 
print(np.median(veri))  #
print(np.std(veri))
print(np.var(veri))

3.0
3.0
1.4142135623730951
2.0


### 2)Minimum ve Maksimum Değerler

In [10]:
print(np.min(veri))
print(np.max(veri))

1
5


### 3)Kümülatif Toplam ve Çarpım

In [12]:
print(np.cumsum(veri))
print(np.cumprod(veri))

[ 1  3  6 10 15]
[  1   2   6  24 120]


Kümülatif toplam, bir veri dizisinin ilk elemanından başlayarak her adımda bir önceki toplam üzerine bir sonraki elemanın eklenmesiyle oluşan bir toplamdır.
Kümülatif çarpım, bir veri dizisinin ilk elemanından başlanarak her adımda önceki çarpımın üzerine yeni çarpım eklenerek gider

# Mantıksal Fonksiyonlar

### 1)Karşılaştırma ve Mantıksal Operasyonlar 

In [13]:
x=np.array([1,2,3])
y=np.array([2,2,3])
print(np.equal(x,y))
print(np.greater(x,y))
print(np.less(x,y))

[False  True  True]
[False False False]
[ True False False]


Diziler arasında karşılaştırma yapar elemanlarını sıraylar karşılaştırır bu karşılaştırma sonucuna göre örneğin equal fonksiyonu x=y mi diye kontrol eder greater fonksiyonu x>y mi diye kontrol eder less fonksiyonu ise x<y mi diye kontrol eder 

### 2) Tümünün veya Birinin Sağlanması

In [15]:
print(np.all([True,True,False])) # Hepsi doğru mu?
print(np.any([True,True,False])) # En az biri doğru mu?

False
True


# Dizi İşlemleri

### 1)Dizi Şekillendirme 

In [16]:
data=np.arange(1,10)
reshaped=data.reshape((3,3))
print(reshaped)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 2)Dizi Birleştirme

In [18]:
x=np.array([1,2,3])
y=np.array([4,5,6])
print(np.concatenate([x,y])) #dizi birleştirme
print(np.hstack([x,y]))   #yatay birleştirme
print(np.vstack([x,y]))   #dikey birleştirme

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


### 3)Dizi Bölme 

In [20]:
z=np.array([1,2,3,4,5,6])
print(np.split(z,2))
#diziyi ortadan ikiye böler 

[array([1, 2, 3]), array([4, 5, 6])]


# Özel Fonksiyonlar


### 1)Meshgrid
Dizi koordinatlarını oluşturur.

In [21]:
x=np.arange(0,5)
y=np.arange(0,5)
X,Y=np.meshgrid(x,y)
print(X)
print(Y)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]


### 2)Linspace
İki değer arasında eşit aralıklı noktalar oluşturur. 

In [23]:
print(np.linspace(0,10,5))
#0 ile 10 arasında 5 nokta 

[ 0.   2.5  5.   7.5 10. ]


### 3)Arange

Belirli bir aralıktaki sayılarla bir dizi oluşturur. 

In [25]:
print(np.arange(1,10,2))
#1 den 10 a kadar 2şer artarak bir dizi oluştur

[1 3 5 7 9]


# Rastgele Sayılar

### 1)Rastgele Değerler

In [27]:
print(np.random.rand(3,3))
#0 ile 1 arasında rasgele sayılar üretir 3x3 boyutunda
print(np.random.randint(1,10,(3,3)))
#1 ile 10 arasında rasgele sayılar üretir 3x3 boyutunda 

[[0.37409411 0.07747725 0.49315949]
 [0.63496819 0.90089954 0.49906666]
 [0.82322251 0.48911525 0.5764534 ]]
[[1 1 4]
 [1 9 1]
 [2 4 4]]


### 2)Rastgele Eleman Seçimi 

In [29]:
data=np.array([10,20,30,40])
print(np.random.choice(data))

20


# Matris İşlemleri

### 1)Transpoze


In [33]:
matris=np.array([[1,2],[3,4]])
print(matris.T)

[[1 3]
 [2 4]]


### 2)Matris Çarpımı

In [34]:
A=np.array([[1,2],[3,4]])
B=np.array([[2,0],[1,2]])
print(np.dot(A,B))

[[ 4  4]
 [10  8]]


### 3)Determinant 

In [35]:
print(np.linalg.det(matris))

-2.0000000000000004


### 4)Ters Matris 

In [37]:
print(np.linalg.inv(matris)) 

[[-2.   1. ]
 [ 1.5 -0.5]]


NumPy'nin bu metodları, özellikle bilimsel hesaplama, veri analizi ve makine öğrenimi projelerinde oldukça faydalıdır.