NumPy'de diziler ve matrisler üzerinde biçimlendirme işlemleri, veri düzenlemeyi ve sunmayı kolaylaştırır. Aşağıda NumPy'nin biçimlendirme işlemleriyle ilgili sık kullanılan yöntemleri ve örneklerini bulabilirsiniz.

## 1. Şekillendirme (Reshaping)

### reshape()
Bir dizinin boyutlarını değiştirir.

In [2]:
import numpy as np
array=np.arange(1,10)
reshaped_array=array.reshape(3,3)
print(array)
print(reshaped_array)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## 2. Düzleştirme (Flattening)

### ravel()
Çok boyutlu bir diziyi tek boyutlu hale getirir.

In [4]:
matrix=np.array([[1,2],[3,4]])
flattened=matrix.ravel()
print(matrix)
print(flattened)

[[1 2]
 [3 4]]
[1 2 3 4]


### flatten()
Benzer şekilde düzleştirme yapar, ancak bir kopya döndürür.

In [5]:
flattened_copy=matrix.flatten()
print(flattened_copy)

[1 2 3 4]


## 3. Transpoze Alma
### transpose()
Dizinin eksenlerini değiştirir. 

In [6]:
matrix=np.array([[1,2,3],[4,5,6]])
transposed=matrix.transpose()
print(transposed)

[[1 4]
 [2 5]
 [3 6]]


### T
Kısa yol olarak kullanılır. 

In [7]:
print(matrix.T)

[[1 4]
 [2 5]
 [3 6]]


## 4. Boyut Ekleme veya Kaldırma
### newaxis
Bir dizinin boyutunu artırır. 

In [8]:
array=np.array([1,2,3])
expanded=array[:,np.newaxis]
print(expanded)

[[1]
 [2]
 [3]]


### squeeze()
Tek boyutlu eksenleri kaldırır.

In [9]:
expanded=np.array([[1],[2],[3]])
squeezed=expanded.squeeze()
print(squeezed)

[1 2 3]


## 5. Eleman Seçimi ve Dilimleme
### Index ile Seçim

In [10]:
array=np.array([10,20,30,40,50])
print(array[1])

20


### Dilimleme

In [11]:
print(array[1:4])

[20 30 40]


### Fancy Indexing
Birden fazla indis ile eleman seçimi.

In [13]:
indices=[0,2,4]
print(array[indices])

[10 30 50]


## 6. Birleştirme ve Bölme
### concatenate()
Dizileri birleştirir.

In [14]:
x=np.array([1,2,3])
y=np.array([4,5,6])
merged=np.concatenate([x,y])
print(merged)

[1 2 3 4 5 6]


In [32]:
x=np.array([[1,2,3],[4,5,6]])
y=np.array([[7,8,9],[10,11,12]])
merged=np.concatenate([x,y])
print(merged)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [34]:
x=np.array([[1,2,3],[4,5,6]])
y=np.array([[7,8,9],[10,11,12]])
merged=np.concatenate([x,y],axis=1)
print(merged)
#axis 1 olarak verilirse yan tarafa ekler ama vermezsek 
#otomatik olarak 0 alır ve altına ekler

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


### split()
Diziyi böler.

In [15]:
array=np.array([1,2,3,4,5,6])
parts=np.split(array,3)
print(parts)

[array([1, 2]), array([3, 4]), array([5, 6])]


## 7. Veri Türü Değiştirme
### astype()
Dizinin elemanlarının veri türünü değiştirir.

In [17]:
array=np.array([1.1,2.2,3.3])
int_Array=array.astype(int)
print(int_Array)

[1 2 3]


## 8. Sıralama ve Düzenleme
### sort()
Bir diziyi sıralar. 

In [19]:
array=np.array([3,4,6,78,2,6,4])
sorted_array=np.sort(array)
print(sorted_array)

[ 2  3  4  4  6  6 78]


### argsort()
Sıralı dizinin indekslerini döndürür.

In [20]:
indices=array.argsort()
print(indices)

[4 0 1 6 2 5 3]


## 9. Ekseni Değiştirme
### swapaxes()
İki ekseni değiştirir.

In [21]:
matrix=np.array([[1,2,3],[4,5,6]])
swapped=matrix.swapaxes(0,1)
print(swapped)

[[1 4]
 [2 5]
 [3 6]]


## 10. Yayılma (Broadcasting)
### Farklı boyutlardaki dizilerle işlemler yapmayı sağlar.

In [22]:
array=np.array([[1,2,3],[4,5,6]])
scalar=10
result=array+scalar
print(result)

[[11 12 13]
 [14 15 16]]


### 11. ndim (Boyut Sayısı)
Bir NumPy dizisinin kaç boyutlu olduğunu verir.

In [23]:
array=np.array([[1,2,3],[4,5,6]])
print(array.ndim)

2


### 12. shape (Şekil)
Bir NumPy dizisinin her boyuttaki eleman sayısını verir.

Bir tuple döner.
İlk değer birinci boyuttaki, ikinci değer ikinci boyuttaki eleman sayısını belirtir.

In [25]:
array=np.array([[1,2,3],[4,5,6]])
print(array.shape)
#2 satır 3 sütun 2,3 değerini döndürür

(2, 3)


### 13. size (Eleman Sayısı)
Bir NumPy dizisindeki toplam eleman sayısını verir. Dizideki elemanların toplam sayısını bir tamsayı olarak döner.

In [27]:
array=np.array([[1,2,3],[4,5,6]])
print(array.size)
#2 satır 3 sütun 2x3 den 6 değerini döndürür

6


### 14. dtype (Veri Türü)
Bir NumPy dizisindeki elemanların veri tipini gösterir.
Dizinin elemanlarının veri türünü (örneğin int32, float64) döner.

In [28]:
array=np.array([1,2,3],dtype=np.float64)
print(array.dtype)

float64
