NumPy, farklı boyutlardaki dizileri birleştirmek için çeşitli yöntemler sunar. Ancak, birleştirme işlemlerinde boyut uyumluluğu önemlidir. İşte farklı boyutlu dizileri birleştirme işlemleri ve kullanılan yöntemler:

### 1. numpy.concatenate() ile Birleştirme

concatenate fonksiyonu, aynı boyuttaki eksenler boyunca dizileri birleştirir. Diziler, belirtilen eksen boyunca birleştirilebilir.

In [2]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6]])
result=np.concatenate((a,b))
print(result)

[[1 2]
 [3 4]
 [5 6]]


In [5]:
result1=np.concatenate((a,b),axis=1)
#gördüğünüz gibi boyutları yanyana birleştirmek 
#için uygun değil bu yüzden hata verdi bu tarz boyutların 
#uygun olmadığı durumlar için vstack ve hstack gibi 
#metodlar kullanılarak bu sorunun üstesinden gelinir

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

### 2. numpy.vstack() ile Dikey Birleştirme
vstack, farklı boyutlu dizileri dikey olarak birleştirir. Dizilerin sütun sayısı aynı olmalıdır.

In [8]:
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])
result = np.vstack((a, b))
print(result)

[[1 2]
 [3 4]
 [5 6]]


### 3. numpy.hstack() ile Yatay Birleştirme
hstack, farklı boyutlu dizileri yatay olarak birleştirir. Dizilerin satır sayısı aynı olmalıdır.


In [7]:
a = np.array([[1], [3]])
b = np.array([[2], [4]])
result = np.hstack((a, b))  # Yatay birleştirme
print(result)

[[1 2]
 [3 4]]


### 4. numpy.expand_dims() ile Boyut Ekleyerek Birleştirme
Farklı boyutlu dizileri birleştirmek için önce bir dizinin boyutunu genişletebilirsiniz. Bu, uyumsuz boyutlu dizileri uyumlu hale getirmek için kullanılır.

In [9]:
a = np.array([1, 2, 3])
b = np.array([[4], [5], [6]])
array1=np.expand_dims(a,axis=1)
result=np.hstack((array1,b))
print(result)

[[1 4]
 [2 5]
 [3 6]]


### 5. numpy.stack() ile Yeni Bir Eksen Ekleyerek Birleştirme
stack, dizileri yeni bir eksende birleştirir. Bu, dizilere ek boyut ekler.

In [10]:
a=np.array([1,2,3])
b=np.array([4,5,6])
result=np.stack((a,b),axis=1)
print(result)

[[1 4]
 [2 5]
 [3 6]]
